# Generated by Django 3.2.4 on 2021-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
