# Generated by Django 3.2.4 on 2021-06-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210626_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.subject'),
        ),
    ]
