# Generated by Django 3.2.4 on 2021-06-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.subject'),
        ),
    ]
