# Generated by Django 3.2.4 on 2021-06-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_content_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.subject'),
        ),
    ]
